# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ICIQ DMP docs
email: dmp@iciq.es
description: > # this means to ignore newlines until "baseurl:"
  Contains the data, tutorials and documentations that are used
  or were generated during the digitalization process of ICIQ, the Institute of
  Chemical Research of Catalonia. Mainly, it contains the documentations of the
  eChempad tool.
author: ICIQ data steward

# Apparently, the deployment to github 4 pages sets the fields baseurl and url for us
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com;

twitter_username: ICIQ
github_username:  AleixMT

# Build settings
markdown: kramdown

# Jekyll theme that we are using
theme: just-the-docs

# Links in the top bar
aux_links:
  eChempad Repository: https://github.com/AleixMT/eChempad
  ICIQ Digitalization panel: https://d.iciq.cat

# Plugins used
plugins:
  - jekyll-default-layout
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, which means that they are not loaded in the server. Use it to exclude files
# that do not have to be loaded, usually files that are not part of the source code
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - makefile
  - README.md
  - LICENSE
  - docker-compose.yml
  - Dockerfile

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logoICIQ.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


# Color scheme supports "light" (default) and "dark"
color_scheme: light


# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true  # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p"  # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ICIQ-DMP/ICIQ-DMP.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

include:
  - _posts
